FROM php:8.1.2-cli-alpine

RUN apk add --no-cache $PHPIZE_DEPS \
    && pecl install xdebug-3.1.3 \
    && docker-php-ext-enable xdebug \
    && apk del $PHPIZE_DEPS

RUN curl -fsSL https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer global require phpunit/phpunit ^9.5.13 --no-progress --no-scripts --no-interaction

ENV PATH /root/.composer/vendor/bin:$PATH

WORKDIR /testing

ENV XDEBUG_MODE=coverage

CMD ["phpunit"]
