name: PHP-CS-Fixer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  fix-style:
    name: PHP-CS-Fixer Enforce Code Style
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: composer update --prefer-dist --no-suggest --no-progress

    - name: Run PHP-CS-Fixer
      run: composer style
      continue-on-error: true

    - name: Don't Commit composer.json change
      run: git checkout -- composer.json

    - name: Don't Commit composer.lock change
      run: git checkout -- composer.lock

    - name: Commit any changes back to the repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[GitHub Action: PHP-CS-Fixer] composer fix-style"
        commit_author: othyn-github-actions <github@othyn.com>
