name: PHPUnit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: [8.1]
        dependency-version: [prefer-lowest, prefer-stable]
        phpunit: [9.5.13]

    name: PHPUnit-${{ matrix.phpunit }} -- PHP-${{ matrix.php }} -- ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          version: ${{ matrix.phpunit }}
          php_version: ${{ matrix.php }}
          php_extensions: xdebug
